== Backend

=== Geth

Antes de comenzar el desarrollo debemos ejecutar un nodo de Ethereum que nos
permita la comunicación con la red y desplegar contratos. Actualmente existen
varios clientes de Ethereum que se pueden utilizar:

* link:https://github.com/ethereum/go-ethereum[*geth*]: Es el cliente oficial
desarrollado por la fundación Ethereum. Está desarrollado con Go. *Es el que
usaremos en este _workshop_*.
* link:https://github.com/paritytech/parity[*parity*]: Es el segundo cliente
más usado. Desarrollado con Rust por Gavin Wood, uno de los fundadores de
Ethereum. Es quizá el cliente más completo, ya que es también un navegador de
DApps.
* link:https://github.com/ethereum/cpp-ethereum[*cpp-ethereum*]: La tercera
implementación más usada, escrita en C++.

Existen otras implementaciones menos usadas en multitud de lenguajes de
programación como JavaScript, Java, Python, Haskell, etc.

==== Instalación

Tenemos varias opciones para instalar Geth. Puesto que está escrito en Go basta
con descargarnos el binario adecuado para nuestra plataforma. También podemos
usar Docker para ejecutarlo. Otra opción sería compilarlo desde las fuentes.

Podemos ejecutar Geth usando Docker con el siguiente comando:

.Ejecutar geth con Docker
[source, bash]
----
docker run -it -p 30303:30303 ethereum/client-go --syncmode=fast
----

Geth usará los llamados `bootnodes` para descubrir nodos en la red. Estos nodos
son especiales ya que sólo se encargan de compartir otros nodos y no de
almacenar la cadena. Al poco de iniciar comenzará a descargar la blockchain de
Ethereum al completo, lo cual es un proceso largo y requiere varios gigabytes
disponibles para almacenar toda la cadena. Además, desplegar un contrato e
interactuar con ellos requiere disponer con una cuenta con ethers para poder
pagar a los mineros.

NOTE: Usando el parámetro `--syncmode=fast` no se computan los estados de la
blockchain sino que ya se descargan computados, lo que hace que sea más rápida
la sincronización.

Afortunadamente existen varias redes de Ethereum actualmente además de la red
principal (_main net_). Estas redes alternativas conocidas como _test nets_
nos permiten desarrollar sin tener que pagar dinero real. Las tres _test nets_
más conocidas son:

* Ropsten
* Kovan
* Rinkeby

.Usar Geth con Ropsten
====
Para conectarnos a una red testing tenemos que indicarle a geth otros
`bootnodes` manualmente:

[source, bash]
----
docker run --rm -it ethereum/client-go --testnet --syncmode=fast --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"
----
====

==== Puppeth

También existe la posibilidad de crear nuestra propia red privada de Ethereum.
*Puppeth* es una utilidad que nos ayuda a crear nuestras propias redes privadas.

****
Haciendo una analogía con un sistema de *integración continua* tendríamos:

* *Red privada*: Entorno de desarrollo
* *_TestNet_*: Entorno de testing
* *_MainNet_*: Entorno de producción
****

Lo primero es generar el bloque génesis de la red, que es
donde se define un estado inicial de la red, por ejemplo, pueden existir
cuentas con ethers desde el primer momento. Puppeth es un CLI que podemos
encontrar en las imágenes de docker etiquetadas como `alltools`.

NOTE: Para crear una red privada puede no ser conveniente usar _proof-of-work_
como protocolo de concenso ya que consume muchos recursos. Como alternativa
tenemos el _proof-of-authority_ que se basa en que sólo unas direcciones
especificadas en el bloque génesis tienen permisos para crear bloques.

El primer paso es generar una dirección de la siguiente forma:

.Generar una dirección
[source, bash]
----
mkdir workshop; cd workshop
docker run --rm -it -v $(pwd):/root/.ethereum/keystore ethereum/client-go:alltools-latest geth account new
----

Una vez introducida la contraseña, nos generará la dirección que se mostrará
por pantalla. Ahora ejecutaremos puppeth:

CAUTION: Como se puede ver, hemos creado la cuenta antes de inicializar la
blockchain. Esto es porque una cuenta no es más que un par de claves pública y
privada, por lo que a una dirección le corresponde una clave privada
independientemente de la blockchain. *No es recomendable usar en la blockchain
principal direcciones que ya hayamos usado en redes privadas o de testing*.

.Ejecutar puppeth
[source, bash]
----
docker run --rm -it -v $(pwd):/data ethereum/client-go:alltools-latest puppeth
----

Puppeth nos pedirá un nombre para nuestra red privada, podemos poner cualquier
cosa, por ejemplo "_workshop_". A continuación mostrará un menú donde tenemos
que elegir la opción `2. Configure new genesis`. Seguiremos los
siguientes pasos:

. Which consensus engine to use?: `2. Clique - proof-of-authority`
. How many seconds should blocks take?: `2`
. Which accounts are allowed to seal?: Aquí introducimos la dirección que
generamos antes.
. Which accounts should be pre-funded?: Aquí también introducimos la dirección
que generamos antes.
. Specify your chain/network ID if you want an explicit one: `random`
. Anything fun to embed into the genesis block?: ``

Una vez generado, volveremos al menú y seleccionaremos la opción
`2. Manage existing genesis`. Y luego `2. Export genesis configuration`. En
el nombre del fichero introduciremos: `/data/workshop.json` y ya tendremos
nuestro bloque génesis generado.

.Inicializar una blockchain usando el bloque génesis generado
[source, bash]
----
docker run --rm -it -v $(pwd):/data ethereum/client-go:alltools-latest geth --datadir /data init /data/workshop.json
----

Ahora podemos iniciar un nodo en nuestra red privada:

.Iniciar un nodo en la blockchain privada
[source, bash]
----
docker run --rm -it -v (pwd):/data -p 8545:8545 ethereum/client-go:alltools-latest geth --networkid 39475 --rpc --rpcaddr 0.0.0.0 --datadir /data console
----

NOTE: El `networkid` si lo generamos aleatoriamente podemos encontrarlo en el
fichero `workshop.json`.

Una vez veamos la consola, procedemos a desbloquear la cuenta autorizada y
comenzar a minar:

.Comenzar proceso de minado
[source, javascript]
----
personal.unlockAccount("0x39091b5f009f21b0dead7320d9487842b0655e12", "password", 0)
miner.start()
----

=== Ganache

Como crear una red privada es un proceso relativamente complejo, existe una
utilidad que nos permite simular una red con el propósito de desarrollar.

NOTE: Anteriormente, `ganache` era conocida como `testrpc`.

Para instalar `ganache` ejecutamos el siguiente comando:

.Instalar ganache-cli
[source, bash]
----
npm install -g ganache-cli
----

Para iniciar una red simplemente ejecutamos el siguiente comando:

.Iniciar red de pruebas
[source, bash]
----
ganache-cli
----

También podemos pasarle una clave privada y una cantidad de ethers para que
`ganache` genere la cuenta automáticamente:

.Iniciar red de pruebas con una cuenta específica
[source, bash]
----
ganache-cli --account="0x54f773ff404a530d7426daf071c098617eb34d54dbe1a198354049125243948a,10000000000000000000"
----

`ganache-cli` es la versión para consola, también podemos usar `ganache` que
tiene una interfaz gráfica. Podemos descargarlo desde
link:http://truffleframework.com/ganache/[http://truffleframework.com/ganache/].

Esta herramienta se comporta como un cliente de Ethereum (como `geth`) ofreciendo
la misma API, pero funciona de forma más rápida ya que no hay que esperar los
15 segundos, los bloques se minan instantáneamente y, por supuesto, sin
ningún coste.

=== Truffle

Truffle es un framework que nos permite automatizar ciertas tareas de desarrollo.
Para crear un nuevo proyecto en Truffle ejecutamos lo siguiente:

.Crear un nuevo proyecto con Truffle
[source, bash]
----
mkdir workshop
cd workshop
truffle init
----

Tendremos la siguiente estructura dentro de nuestro directorio `workshop`:

[source]
----
├── build
│   └── contracts
│       └── Migrations.json
├── contracts
│   └── Migrations.sol
├── migrations
│   └── 1_initial_migration.js
├── test
├── truffle-config.js
└── truffle.js
----

* *build*: Contiene la ABI de los contratos. La ABI se almacena en un fichero
con formato JSON. Usaremos la ABI contiene la información para interactuar
con nuestro contrato.
* *contracts*: Contiene el código fuente de los contratos que vamos a
desarrollar.
* *migrations*: Contiene las migraciones. Las migraciones son scripts que se
ejecutan cuando actualizamos nuestro contratos.
* *test*: Contiene los tests para nuestros contratos.
* *truffle-config.js / truffle.js*: Contiene la configuración para el
despligue de los contratos.

Para compilar un contrato (generar su ABI) ejecutamos:

.Compilar un Smart Contract
[source, bash]
----
truffle compile
----

Para desplegar un Smart Contract:

.Desplegar un Smart Contract
[source, bash]
----
truffle migrate
----

NOTE: Para que funcione el despliegue de un Smart Contract debemos tener
`ganache-cli` funcionando mientras realizamos el despliegue.

==== Infura

Para desplegar a una testnet en lugar de desplegar a ganache necesitamos uno
nodo que esté conectado a la testnet en cuestión y *esté sincronizado*. Una
forma de evitar tener que correr un nodo conectado a las testnet es usar
link:https://infura.io/[Infura]. Con Infura disponemos de un nodo público que
nos da acceso a diferentes redes de Ethereum.

Para usar infura con truffle añadiremos los siguiente al fichero `truffle.js`:

.`truffle.js`
[source, javascript]
----
require('dotenv').config();
const Wallet = require('ethereumjs-wallet');
const WalletProvider = require('truffle-wallet-provider');
const Web3 = require('web3');

const web3 = new Web3();

var privateKey = new Buffer('<my private key>', 'hex');

module.exports = {
  networks: {
    ropsten: {
      provider: new WalletProvider(
        Wallet.fromPrivateKey(ropstenPrivateKey),
        'https://ropsten.infura.io/',
      ),
      gas: 4600000,
      gasPrice: web3.toWei('20', 'gwei'),
      network_id: '3',
    },
  },
};
----

Debemos instalar los siguientes paquetes:

.Instalación de paquetes adicional
[source, bash]
----
npm install --save dotenv truffle-wallet-provider
----
